-- Table: sentences
CREATE TABLE sentences (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    japanese TEXT NOT NULL,
    english TEXT NOT NULL,
    page INT UNSIGNED NOT NULL,
    is_reported BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table: answer_histories
CREATE TABLE answer_histories (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sentence_id INT UNSIGNED NOT NULL,
    is_correct BOOLEAN NOT NULL,
    incorrect_answer TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (sentence_id) REFERENCES sentences(id)
);
